apiVersion: apps/v1
kind: Deployment
metadata:
  name: timvault-operator-controller
  namespace: timvault-operator-system
  labels:
    app: timvault-operator
    control-plane: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timvault-operator
      control-plane: controller-manager
  template:
    metadata:
      labels:
        app: timvault-operator
        control-plane: controller-manager
    spec:
      serviceAccountName: timvault-operator
      containers:
        - name: manager
          image: timvault-operator:latest
          imagePullPolicy: IfNotPresent
          command:
            - /manager
          args:
            - --leader-elect
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
            - containerPort: 8081
              name: health
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 65532
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 10

