apiVersion: secrets.tim.operator/v1alpha1
kind: TimSecret
metadata:
  name: myapp-secrets
  namespace: default
spec:
  # Reference to TimSecretConfig
  vaultConfig: vault-config
  vaultConfigNamespace: vault-system  # Can reference config from another namespace
  
  # Path in Vault where secrets are stored
  vaultPath: "secret/data/myapp"
  
  # Name of the Kubernetes Secret to create
  secretName: "myapp-secrets"
  
  # Optional: Deployment to restart when secrets change
  deploymentName: "myapp"
