apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: timsecrets.secrets.tim.operator
spec:
  group: secrets.tim.operator
  names:
    kind: TimSecret
    listKind: TimSecretList
    plural: timsecrets
    singular: timsecret
    shortNames:
      - ts
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - vaultPath
                - secretName
              properties:
                vaultConfig:
                  type: string
                  description: Name of the TimSecretConfig to use
                vaultConfigNamespace:
                  type: string
                  description: Namespace of the TimSecretConfig
                vaultURL:
                  type: string
                  description: Vault server URL (direct value, overrides vaultConfig)
                vaultToken:
                  type: string
                  description: Authentication token for Vault (direct value, overrides vaultConfig)
                vaultPath:
                  type: string
                  description: Path in Vault where secrets are stored
                secretName:
                  type: string
                  description: Name of the Kubernetes Secret to create
                deploymentName:
                  type: string
                  description: Name of the Deployment to restart when secret changes
                namespace:
                  type: string
                  description: Namespace where the secret and deployment are located
                syncInterval:
                  type: string
                  default: "5m"
                  description: Interval between syncs from Vault (e.g., "30s", "1m", "5m"). Default is 5m. Min 30s, Max 1h.
            status:
              type: object
              properties:
                lastSyncTime:
                  type: string
                  format: date-time
                  description: Last time the secret was synced from Vault
                secretHash:
                  type: string
                  description: Hash of the secret data for change detection
                retryCount:
                  type: integer
                  description: Number of consecutive failed sync attempts
                lastError:
                  type: string
                  description: Last error encountered during sync
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Vault Path
          type: string
          jsonPath: .spec.vaultPath
        - name: Secret Name
          type: string
          jsonPath: .spec.secretName
        - name: Sync Interval
          type: string
          jsonPath: .spec.syncInterval
        - name: Retries
          type: integer
          jsonPath: .status.retryCount
        - name: Last Sync
          type: date
          jsonPath: .status.lastSyncTime
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
