name: Publish CRDs

on:
  push:
    branches:
      - main
    paths:
      - 'config/crd/*.yaml'
      - 'api/v1alpha1/*_types.go'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create CRDs artifact
        run: |
          mkdir -p dist
          
          # Combine CRDs into single file
          cat > dist/crds.yaml <<EOF
          # TimVault Operator CRDs
          # Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
          # Commit: ${{ github.sha }}
          
          ---
          $(cat config/crd/timsecret-crd.yaml)
          ---
          $(cat config/crd/timsecretconfig-crd.yaml)
          EOF
          
          # Copy individual CRDs
          cp config/crd/timsecret-crd.yaml dist/
          cp config/crd/timsecretconfig-crd.yaml dist/

      - name: Upload CRDs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: crds
          path: dist/
          retention-days: 90

      - name: Commit and push to gh-pages (optional)
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Create or update gh-pages branch
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages
          
          # Clear everything except dist
          git rm -rf . || true
          
          # Copy CRDs
          cp -r dist/* .
          
          # Commit and push
          git add .
          git commit -m "Update CRDs from commit ${{ github.sha }}" || echo "No changes to commit"
          git push origin gh-pages --force

